typle_=(1,2,"a",True,"String")
immutable_var_=typle_
print(immutable_var_)
immutable_var_2=typle_
immutable_var_2=2,3,"apple",False
print(immutable_var_2)
mutable_list=[10,20,30,"banana",True]
print(mutable_list)
mutable_list[1]=40
print(mutable_list)
mutable_list.extend(["string",5])
print(mutable_list)
mutable_list.append("coconut")
print(mutable_list)
mutable_list.extend("Svetlana")
print(mutable_list)
print(typle_.__sizeof__())
print(mutable_list.__sizeof__())
typle_2=([10,20],30)
print(typle_2)
typle_2[0][1]=50
print(typle_2)
typle_2=([10,20],30)+(1,2)
print(typle_2)
typle_2=([10,20],30)*5
print(typle_2)